// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ytVw5gItaASYr8yIanxkuYe3pJoe2f0',
    appId: '1:408750961465:web:00034ff9d3f51000586ee8',
    messagingSenderId: '408750961465',
    projectId: 'the-logistics',
    authDomain: 'the-logistics.firebaseapp.com',
    storageBucket: 'the-logistics.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzyV4Ck5bkgTm1ECJ0V9Lwi6TEFO_c3Ag',
    appId: '1:408750961465:android:6a9f5a031facb8d6586ee8',
    messagingSenderId: '408750961465',
    projectId: 'the-logistics',
    storageBucket: 'the-logistics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkEzb5SbaKjYQ9IER8N1nYsSh7qju39Ak',
    appId: '1:408750961465:ios:06f2b4be8821db55586ee8',
    messagingSenderId: '408750961465',
    projectId: 'the-logistics',
    storageBucket: 'the-logistics.appspot.com',
    iosClientId: '408750961465-6dd2j70r5j39pjtc9s853euitatbfjnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chstores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkEzb5SbaKjYQ9IER8N1nYsSh7qju39Ak',
    appId: '1:408750961465:ios:06f2b4be8821db55586ee8',
    messagingSenderId: '408750961465',
    projectId: 'the-logistics',
    storageBucket: 'the-logistics.appspot.com',
    iosClientId: '408750961465-6dd2j70r5j39pjtc9s853euitatbfjnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chstores',
  );
}
